module: src.client.agents.HTTPAgentOpenAI
parameters:
  url: https://api.openai.com/v1/chat/completions
  headers:
    Content-Type: application/json
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
  api_key_list_file: configs/apikeys/shared/openai_keys.json
  max_retries: 10
