import: definition.yaml

concurrency:
  task:
    kg-dev: 1
  agent:
    gpt-3.5-turbo-0613: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo-0613
    task:
      - kg-dev

output: "outputs/{TIMESTAMP}"
