import: definition.yaml

concurrency:
  task:
    kg-grailqa-dev-800-1000: 1
  agent:
    gpt-3.5-turbo-0613: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo-0613
    task:
      - kg-grailqa-dev-800-1000

output: "outputs/grailqa_dev_800_1000_{TIMESTAMP}"
